In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df = pd.read_csv("D:\Crop recommend system that analyse temperature from API of app that showing diffrent locations tempeture\Crop_recommendation.csv")
df.reset_index(inplace = True)
df.head()


<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Devanshi\AppData\Local\Temp\ipykernel_8132\3888592349.py:1: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv("D:\Crop recommend system that analyse temperature from API of app that showing diffrent locations tempeture\Crop_recommendation.csv")


,index,N,P,K,temperature,humidity,ph,rainfall,label
0,0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [3]:
df.shape

(2200, 9)

In [4]:
features = ['N' , 'P' , 'K' , 'temperature','humidity','ph','rainfall','label']
df[features].head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [5]:
print(df.columns)

Index(['index', 'N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall',
       'label'],
      dtype='object')


In [6]:
df[features].isnull().values.any()

np.False_

In [7]:
def combine_features(row):
    return row['N']+' '+row['P']+' '+row['K']+' '+row['temperature']+' '+row['humidity']+' '+row['ph']+' '+row['raifall']+' '+row['label']

In [8]:
count_matrix = CountVectorizer().fit_transform(df['label'])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]


In [9]:
cosine_sim.shape

(2200, 2200)

In [10]:
def get_crops_for_temperature(temp):
    suitable = df[df['temperature'] == temp]
    
    if suitable.empty:
        return f"No crops found for {temp}°C"
    return suitable['label'].tolist()

In [11]:
def get_crops_for_temperature(temp, top_n=3):
    # Calculate absolute difference
    df['temp_diff'] = abs(df['temperature'] - temp)
    
    # Get the top_n crops with smallest difference
    suitable = df.nsmallest(top_n, 'temp_diff')
    
    return suitable['label'].tolist()

In [12]:
user_temp = 26
friendly_crops = get_crops_for_temperature(user_temp)
print("Temperature-friendly crops:", friendly_crops)

Temperature-friendly crops: ['coconut', 'coffee', 'cotton']


In [13]:
print(get_crops_for_temperature(26, top_n=5))

['coconut', 'coffee', 'cotton', 'banana', 'pigeonpeas']
